server:
  port: 8888
aliyun:
  sms:
    access-key-secret:
    access-key-id:
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.200:8848,192.168.211.200:8849,192.168.211.200:8850
  application:
    name: third-party