server:
  port: 32000
spring:
  application:
    name: anime
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.200/anime?useSSL=true&useUnicode=true&characterEncoding=UTF-8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.211.200:8848,192.168.211.200:8849,192.168.211.200:8850