@startuml
participant 前端
participant 后端
participant 数据库

activate 前端
前端 -> 后端: 发送收藏请求
activate 后端
后端 -> 数据库: 保存收藏信息
activate 数据库
数据库 --> 后端: 收藏信息保存成功
deactivate 数据库
后端 -> 后端: 处理收藏请求
后端 -> 数据库: 获取收藏信息
activate 数据库
数据库 --> 后端: 返回收藏信息
deactivate 数据库
后端 -> 前端: 返回收藏信息
deactivate 后端
deactivate 前端
@enduml